export declare const labels: {
    'head-age-less|more': string;
    'Head skinny-fat': string;
    'head-angle-in|out': string;
    'head-oval': string;
    'head-round': string;
    'head-rectangular': string;
    'head-square': string;
    'head-triangular': string;
    'head-invertedtriangular': string;
    'head-diamond': string;
    'Scale depth of parietal side': string;
    'Scale depth': string;
    'Scale horizontally': string;
    'Scale vertically': string;
    'Move horizontally': string;
    'Move vertically': string;
    'Move depth': string;
    'Cranic shape': string;
    'Temple bulge': string;
    'Eyebrows angle': string;
    'Move vert': string;
    'Double neck': string;
    'Move horizontally.': string;
    'Scale depth of nape': string;
    'Eye bag volume': string;
    'Eye bag distorsion': string;
    'Eye bag height': string;
    'Eyefold angle': string;
    'Eye epicanthus': string;
    'Eyefold volume': string;
    'Eyefold position': string;
    'Scale height 1': string;
    'Scale height 2': string;
    'Scale height 3': string;
    'Move outer corner horiz.': string;
    'Move inner corner horiz.': string;
    'Move eye horizontally': string;
    'Move eye vertically': string;
    'Scale eye': string;
    'Move outer corner vert.': string;
    'Move inner corner vert.': string;
    'Scale nostrils width': string;
    'Scale tip width': string;
    'Move base vert.': string;
    'Scale width 1': string;
    'Scale width 2': string;
    'Scale width 3': string;
    'nose-compression-compress|uncompress': string;
    'nose-curve-concave|convex': string;
    'nose-greek-lessgreek|moregreek': string;
    'nose-hump-lesshump|morehump': string;
    'nose-volume-potato|point': string;
    'nose-nostrils-angle-down|up': string;
    'Move tip vertically': string;
    'Septum Angle': string;
    'Scale nostrils flaring': string;
    'Scale lowerlip height': string;
    'Scale lowerlip width': string;
    'Scale upperlip height': string;
    'Scale upperlip width': string;
    'Cupid\'s bow width': string;
    'Dimples': string;
    'Laugh-lines': string;
    'Lowerlip curved shape': string;
    'Move corners vert.': string;
    'Scale middle lowerlip': string;
    'Scale lowerlip volume': string;
    'Scale philtrum volume': string;
    'Scale upperlip volume': string;
    'Upperlip curved shape': string;
    'Scale middle upperlip': string;
    'Cupid\'s bow shape': string;
    'Scale ear': string;
    'Scale height': string;
    'Scale lobe': string;
    'Ear shape (pointed-triangle)': string;
    'Ear rotation': string;
    'Ear shape (squared-round)': string;
    'Scale width': string;
    'Ear wing-shaped': string;
    'Ear flapped': string;
    'Tone of side chin': string;
    'Cleft chin': string;
    'Scale chin prominence': string;
    'Scale chin width': string;
    'Scale chin height': string;
    'Scale chin angular': string;
    'Scale chin prognathism': string;
    'Cheek outer volume': string;
    'Scale cheek prominence': string;
    'Cheek inner volume': string;
    'Scale cone-shape': string;
    'Dorsi muscle': string;
    'Pectoral muscle': string;
    'Waist vertical position': string;
    'Muscular tone': string;
    'Pregnancy shape': string;
    'Navel bump': string;
    'Navel position': string;
    'Buttocks volume': string;
    'Pelvis muscular tone': string;
    'Genital volume': string;
    'Fingers distance': string;
    'Fingers diameter': string;
    'Fingers length': string;
    'Scale hand': string;
    'Hand position': string;
    'Scale foot': string;
    'Shoulder muscle mass': string;
    'Lowerarm thickness 1': string;
    'Lowerarm length': string;
    'Lowerarm thickness 2': string;
    'Lowerarm skinny-fat': string;
    'Lowerarm muscles': string;
    'Upperarm thickness 1': string;
    'Upperarm length': string;
    'Upperarm thickness 2': string;
    'Upperarm skinny-fat': string;
    'Upperarm muscles': string;
    'Move knee horizontally': string;
    'Lowerleg scale depth': string;
    'Lowerleg scale horizontally': string;
    'Lowerleg skinny-fat': string;
    'Lowerleg muscle': string;
    'Upperleg scale depth': string;
    'Upperleg scale horizontally': string;
    'Move knee vertically': string;
    'Upperleg skinny-fat': string;
    'Upperleg muscle': string;
    'Upperleg height': string;
    'Lowerleg height': string;
    'Breast size': string;
    'Breast firmness': string;
    'Vertical position': string;
    'Horizontal distance': string;
    'Pointiness': string;
    'Breast Volume': string;
    'Nipple size': string;
    'Nipple point': string;
    'Penis length': string;
    'Penis circumference': string;
    'Testicles size': string;
    'Gender': string;
    'Age': string;
    'Muscle': string;
    'Weight': string;
    'Height': string;
    'Proportions': string;
    'African': string;
    'Asian': string;
    'Caucasian': string;
};
export declare const groups: {
    'Face': string;
    'head shape': string;
    'head size': string;
    'forehead': string;
    'eyebrows': string;
    'neck': string;
    'right eye': string;
    'left eye': string;
    'nose size': string;
    'nose size details': string;
    'nose features': string;
    'mouth size': string;
    'mouth size details': string;
    'mouth features': string;
    'right ear': string;
    'left ear': string;
    'chin/jaw': string;
    'left cheek': string;
    'right cheek': string;
    'Torso': string;
    'Hip': string;
    'Stomach': string;
    'Buttocks': string;
    'Pelvis': string;
    'Arms and Legs': string;
    'right hand': string;
    'left hand': string;
    'right foot': string;
    'left foot': string;
    'left shoulder': string;
    'right shoulder': string;
    'right arm': string;
    'left arm': string;
    'right leg': string;
    'left leg': string;
    'legs': string;
    'Gender': string;
    'Breast': string;
    'Genitals': string;
    'Macro modelling': string;
    'Macro': string;
};
export declare const clothes: {
    'Женская одежда': {
        'Блузки': string[];
        'Платья': string[];
        'Нижнее белье': string[];
        'Шорты': string[];
        'Обувь': string[];
        'Перчатки': string[];
        'Костюм': string[];
        'Юбки': string[];
    };
    'Мужская одежда': {
        'Костюм': string[];
    };
    'Уни': {
        'Аксессуары': string[];
        'Костюм': never[];
        'Халаты': string[];
        'Головные уборы': string[];
        'Перчатки': string[];
        'Обувь': string[];
        'Брюки': string[];
    };
};
