export const labels = {
  'head-age-less|more': 'голова возраст-меньше|больше',
  'Head skinny-fat': 'Глава скинни фэт',
  'head-angle-in|out': 'угол-в голову|отъезда',
  'head-oval': 'саморез',
  'head-round': 'круглая голова',
  'head-rectangular': 'голова прямоугольная',
  'head-square': 'голова квадратная',
  'head-triangular': 'голова треугольная',
  'head-invertedtriangular': 'глава invertedtriangular',
  'head-diamond': 'головка Диаманта',
  'Scale depth of parietal side': 'Шкала глубины теменной стороне',
  'Scale depth': 'Шкала глубины',
  'Scale horizontally': 'Масштаб по горизонтали',
  'Scale vertically': 'Масштаб по вертикали',
  'Move horizontally': 'Двигаться по горизонтали',
  'Move vertically': 'Двигаться по вертикали',
  'Move depth': 'Двигаться глубина',
  'Cranic shape': 'Формы Cranic ',
  'Temple bulge': 'Храм выпирать',
  'Eyebrows angle': 'Угол брови ',
  'Move vert': 'Перемещение Верт',
  'Double neck': 'Двойной шеи',
  'Move horizontally.': 'Двигаться по горизонтали.',
  'Scale depth of nape': 'Шкала глубины затылка',
  'Eye bag volume': 'Объем мешка глаза ',
  'Eye bag distorsion': 'Мешок глаз искажения',
  'Eye bag height': 'Мешок глаз высота',
  'Eyefold angle': 'Угол Eyefold ',
  'Eye epicanthus': 'Эпикантус глаз ',
  'Eyefold volume': 'Объем Eyefold ',
  'Eyefold position': 'Положение Eyefold ',
  'Scale height 1': 'Масштаб высоты 1',
  'Scale height 2': 'Масштаб высоты 2',
  'Scale height 3': 'Масштаб высоты 3',
  'Move outer corner horiz.': 'Перемещение наружного угла гориз.',
  'Move inner corner horiz.': 'Перемещение внутреннего угла гориз.',
  'Move eye horizontally': 'Движение глаз по горизонтали',
  'Move eye vertically': 'Движение глаз вертикально',
  'Scale eye': 'Шкалы глаз',
  'Move outer corner vert.': 'Перемещение наружного угла Верт.',
  'Move inner corner vert.': 'Перемещение внутреннего угла Верт.',
  'Scale nostrils width': 'Шкала ширины ноздрей ',
  'Scale tip width': 'Шкала ширина наконечника ',
  'Move base vert.': 'Переместить базу Верт.',
  'Scale width 1': 'Шкала ширина 1',
  'Scale width 2': 'Шкала ширина 2',
  'Scale width 3': 'Шкала ширина 3',
  'nose-compression-compress|uncompress': 'сжатие-сжатие нос|распаковка',
  'nose-curve-concave|convex': 'кривой нос вогнутый|выпуклый',
  'nose-greek-lessgreek|moregreek': 'нос греческий-lessgreek|moregreek',
  'nose-hump-lesshump|morehump': 'горб-lesshump нос|morehump',
  'nose-volume-potato|point': 'объем-картофельный нос|точка',
  'nose-nostrils-angle-down|up': 'ноздри-угол-нос вниз|вверх',
  'Move tip vertically': 'Переместить кончик вертикально',
  'Septum Angle': 'Угол Перегородки ',
  'Scale nostrils flaring': 'Масштаб ноздри его раздувались',
  'Scale lowerlip height': 'Масштаб высоты lowerlip ',
  'Scale lowerlip width': 'Шкала ширина lowerlip ',
  'Scale upperlip height': 'Масштаб высоты верхней губой ',
  'Scale upperlip width': 'Шкала ширина верхней губой ',
  'Cupid\'s bow width': 'Ширина губки бантиком ',
  'Dimples': 'Ямочки',
  'Laugh-lines': 'Мимические морщины',
  'Lowerlip curved shape': 'Lowerlip изогнутой формы',
  'Move corners vert.': 'Перемещать углы Верт.',
  'Scale middle lowerlip': 'Масштаб среднего lowerlip',
  'Scale lowerlip volume': 'Шкалы громкости lowerlip ',
  'Scale philtrum volume': 'Шкалы громкости Желобок ',
  'Scale upperlip volume': 'Шкалы громкости верхней губой ',
  'Upperlip curved shape': 'Верхней губой изогнутой формы',
  'Scale middle upperlip': 'Шкала середине верхней губой',
  'Cupid\'s bow shape': 'Формы лука Купидона ',
  'Scale ear': 'Масштаб ухо',
  'Scale height': 'Масштаб высоты',
  'Scale lobe': 'Масштаб доле',
  'Ear shape (pointed-triangle)': 'Форма уха (отмечено треугольником)',
  'Ear rotation': 'Вращение ухо ',
  'Ear shape (squared-round)': 'Ухо форма (квадрат, круглый)',
  'Scale width': 'Шкала ширина',
  'Ear wing-shaped': 'Крыло в форме уха',
  'Ear flapped': 'Ухо захлопали',
  'Tone of side chin': 'Тон стороне подбородка',
  'Cleft chin': 'Раздвоенный подбородок',
  'Scale chin prominence': 'Шкала подбородок известность',
  'Scale chin width': 'Шкала ширина подбородка ',
  'Scale chin height': 'Масштаб высоты подбородка ',
  'Scale chin angular': 'Шкала подбородок угловой',
  'Scale chin prognathism': 'Шкала подбородок прогнатизм',
  'Cheek outer volume': 'Щеки внешний объем',
  'Scale cheek prominence': 'Масштаб щеку известность',
  'Cheek inner volume': 'Щеки внутренний объем',
  'Scale cone-shape': 'Шкала форму конуса ',
  'Dorsi muscle': 'Мышцы спины',
  'Pectoral muscle': 'Грудные мышцы',
  'Waist vertical position': 'Талия вертикальном положении',
  'Muscular tone': 'Мышечный тонус',
  'Pregnancy shape': 'Формы беременности ',
  'Navel bump': 'Бугорок пупка ',
  'Navel position': 'Положение пупка ',
  'Buttocks volume': 'Объем ягодиц ',
  'Pelvis muscular tone': 'Таз мышечного тонуса',
  'Genital volume': 'Объем половых органов ',
  'Fingers distance': 'Пальцами расстояние',
  'Fingers diameter': 'Пальцы диаметр',
  'Fingers length': 'Длина пальцев ',
  'Scale hand': 'Шкала силы',
  'Hand position': 'Положение рук ',
  'Scale foot': 'Шкала ноги',
  'Shoulder muscle mass': 'Плечо мышечной массы',
  'Lowerarm thickness 1': 'Толщина Lowerarm 1',
  'Lowerarm length': 'Длина Lowerarm ',
  'Lowerarm thickness 2': 'Толщина Lowerarm 2',
  'Lowerarm skinny-fat': 'Lowerarm скинни фэт',
  'Lowerarm muscles': 'Lowerarm мышц',
  'Upperarm thickness 1': 'Толщина упор на полу на обеих 1',
  'Upperarm length': 'Длина упор на полу на обеих ',
  'Upperarm thickness 2': 'Упор на полу на обеих толщина 2',
  'Upperarm skinny-fat': 'Упор на полу на обеих скинни фэт',
  'Upperarm muscles': 'Упор на полу на обеих мышц',
  'Move knee horizontally': 'Двигаться по колено горизонтально',
  'Lowerleg scale depth': 'Масштаб Lowerleg глубина',
  'Lowerleg scale horizontally': 'Масштаб Lowerleg горизонтально',
  'Lowerleg skinny-fat': 'Lowerleg скинни фэт',
  'Lowerleg muscle': 'Lowerleg мышцы',
  'Upperleg scale depth': 'Масштаб Upperleg глубина',
  'Upperleg scale horizontally': 'Масштаб Upperleg горизонтально',
  'Move knee vertically': 'Двигаться по колено вертикально',
  'Upperleg skinny-fat': 'Upperleg скинни фэт',
  'Upperleg muscle': 'Upperleg мышцы',
  'Upperleg height': 'Высота Upperleg ',
  'Lowerleg height': 'Высота Lowerleg ',
  'Breast size': 'Размер груди ',
  'Breast firmness': 'Груди упругость',
  'Vertical position': 'Вертикальное положение',
  'Horizontal distance': 'Горизонтальное расстояние',
  'Pointiness': 'Pointiness',
  'Breast Volume': 'Объем Груди ',
  'Nipple size': 'Размер ниппель ',
  'Nipple point': 'Точки соска ',
  'Penis length': 'Длина пениса ',
  'Penis circumference': 'Обхват пениса ',
  'Testicles size': 'Размер тестикулы ',
  'Gender': 'Гендер',
  'Age': 'Возраст',
  'Muscle': 'Мышцы',
  'Weight': 'Вес',
  'Height': 'Высота',
  'Proportions': 'Пропорции',
  'African': 'Африки',
  'Asian': 'Азии',
  'Caucasian': 'Кавказские'
};
export const groups = {
  'Face': 'Лицо',
  'head shape': 'форма головы',
  'head size': 'размер головы ',
  'forehead': 'лоб',
  'eyebrows': 'брови',
  'neck': 'шея',
  'right eye': 'правый глаз',
  'left eye': 'левый глаз',
  'nose size': 'размер носа ',
  'nose size details': 'детали размер носа ',
  'nose features': 'особенности носа ',
  'mouth size': 'размер рта ',
  'mouth size details': 'детали размер рта ',
  'mouth features': 'рот характеристики',
  'right ear': 'правое ухо',
  'left ear': 'левое ухо',
  'chin/jaw': 'подбородок/челюсть',
  'left cheek': 'левую щеку',
  'right cheek': 'правую щеку',
  'Torso': 'Туловище',
  'Hip': 'Бедра',
  'Stomach': 'Желудок',
  'Buttocks': 'Ягодицы',
  'Pelvis': 'Таз',
  'Arms and Legs': 'Руки и ноги',
  'right hand': 'правая рука',
  'left hand': 'левой рукой',
  'right foot': 'правая нога',
  'left foot': 'левой ногой',
  'left shoulder': 'левое плечо',
  'right shoulder': 'правое плечо',
  'right arm': 'правая рука',
  'left arm': 'левая рука',
  'right leg': 'правая нога',
  'left leg': 'левую ногу',
  'legs': 'ноги',
  'Gender': 'Гендер',
  'Breast': 'Груди',
  'Genitals': 'Гениталии',
  'Macro modelling': 'Макро моделирования',
  'Macro': 'Макрос'
};
export const clothes = {
  'Женская одежда': {
    'Блузки': [
      'Asymmetric_Tunic_and_Sash',
      'Harvey_Sweater2',
      'Harvey_VestV1',
      'Rolled_neck_blouse',
      'Sleeveless',
      'Tank_Top_01',
      'TubeTop',
      'VNeckTop',
      'short_tail_camo_tee'
    ],
    'Платья': [
      'Babydoll',
      'Cocktaildress',
      'F_Dress_01',
      'F_Dress_02',
      'F_Dress_03',
      'F_Dress_04',
      'Sari1',
      'TubeDress'
    ],
    'Нижнее белье': [
      'BrazBikiniBra',
      'BrazBikiniSlip',
      'F_Bikini_01',
      'F_Beach_Dress_01',
      'F_One-piece_Swimsuit_01',
      'String3',
      'Teddy',
      'bandbikinibra',
      'bandbikinislip',
      'bandeau_bra',
      'female_panties_01',
      'female_top_01',
      'frenchbra',
      'spaghetti-top',
      'transparent_bra'
    ],
    'Шорты': [
      'JeansSkirt',
      'ShortJeans'
    ],
    'Обувь': [
      'WinterBoots'
    ],
    'Перчатки': [
      'armsleeve_fishnet_medium',
      'armsleeve_white_s'
    ],
    'Костюм': [
      'female_elegantsuit01',
      'female_casualsuit01',
      'female_casualsuit02',
      'female_sportsuit01'
    ],
    'Юбки': [
      'miniskirt'
    ]
  },
  'Мужская одежда': {
    'Костюм': [
      'male_casualsuit01',
      'male_casualsuit02',
      'male_casualsuit03',
      'male_casualsuit04',
      'male_casualsuit05',
      'male_casualsuit06',
      'male_elegantsuit01',
      'male_worksuit01'
    ]
  },
  'Уни': {
    'Аксессуары': [
      'glasses',
    ],
    'Костюм': [],
    'Халаты': [
      'Coat'
    ],
    'Головные уборы': [
      'Fishing_Hat_01',
      'fedora',
      'fedora_cocked',
      'pith_helmet'
    ],
    'Перчатки': [
      'Harvey_MadScientistGlovesV1'
    ],
    'Обувь': [
      'shoes01',
      'shoes02',
      'shoes03',
      'shoes04',
      'shoes05',
      'shoes06'
    ],
    'Брюки': [
      'Harvey_PantsBootsV1',
      'Tightjeans'
    ]
  }
};
